name: Build Final Flutter App

on: workflow_dispatch

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.0'
      - run: flutter pub get

      - run: mkdir -p ${{ github.workspace }}/build/windows/x64/runner/Release
      - run: flutter build windows
      - name: List Windows Build Directory
        run: dir ${{ github.workspace }}/build/windows/x64/runner/Release
      - name: zip everything
        run: |
          cd ${{ github.workspace }}/build/windows/x64/runner/Release
          powershell -Command "Compress-Archive -Path * -DestinationPath mirarr-windows.zip"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: ${{ github.workspace }}/build/windows/x64/runner/Release/mirarr-windows.zip

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.0'
      - run: sudo apt-get update
      - run: sudo apt-get install -y ninja-build cmake libgtk-3-dev
      - run: flutter pub get

      - run: mkdir -p ${{ github.workspace }}/build/linux/x64/release/bundle
      - run: flutter build linux
      - name: List Linux Build Directory
        run: ls -alh ${{ github.workspace }}/build/linux/x64/release/bundle
      - name: zip everything
        run: |
          cd ${{ github.workspace }}/build/linux/x64/release/bundle
          zip -r mirarr.zip *
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-zip
          path: ${{ github.workspace }}/build/linux/x64/release/bundle/mirarr.zip

  upload-release:
    permissions: write-all
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download Windows ZIP
        uses: actions/download-artifact@v4
        with:
          name: windows-zip
          path: ./out/windows

      - name: Download Linux ZIP
        uses: actions/download-artifact@v4
        with:
          name: linux-zip
          path: ./out/linux

      - name: List output directory
        run: ls -R ./out

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          files: |
            ./out/windows/*
            ./out/linux/*
          tag_name: ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false